"""A module to represent the game state and logic.
"""


from constants import LIFE_POINTS
from enums import GuessResult


class Game:
    """
    A class to represent the game state.
    Attributes:
        life (int): The number of lives the player has.
        score (int): The player's current score.
        altered_regions (list[tuple[int, int, int, int]]):
            A list of tuples representing the regions that have been altered.
            The tuple format is (x, y, width, height).
        found_regions (list[tuple[int, int, int, int]]):
            A list of tuples representing the regions that have been foundr.
            The tuple format is (x, y, width, height).
    """
    def __init__(self):
        """Instance initialisation, sets default values for the game state."""
        self.score = 0
        self.life = 0
        self.remaining = 0
        self.altered_regions = []
        self.found_regions = []

    def start_game(
            self, altered_regions: list[tuple[int, int, int, int]]) -> None:
        """
        Starts a new game with given altered regions.
        Scores are not reset.
        Args:
            altered_regions: Generated by ImageProcessor
                The tuple format is (x, y, width, height)
        """
        self.life = LIFE_POINTS
        self.remaining = len(altered_regions)
        self.altered_regions = altered_regions
        self.found_regions = []

    def guess(self, x, y) -> GuessResult:
        """Processes a player's guess at the given coordinates.
        Args:
            x: The x-coordinate of the guess.
            y: The y-coordinate of the guess.
        Returns:
            GuessResult: An enum indicating the result of the guess.
                CORRECT, INCORRECT, ALREADY_FOUND, WIN, LOSE, or GAME_OVER.
        """
        if self.life <= 0 or self.remaining <= 0:
            return GuessResult.GAME_OVER  # Ignore guesses if game is over
        for region in self.altered_regions:
            # Check if the guess is within the altered region
            if (region[0] <= x <= region[0] + region[2] and
                    region[1] <= y <= region[1] + region[3]):
                if region in self.found_regions:
                    return GuessResult.ALREADY_FOUND  # Skip if already found
                self.found_regions.append(region)
                self.score += 1
                self.remaining -= 1

                if self.remaining == 0:
                    return GuessResult.WIN  # All regions found, game over
                return GuessResult.CORRECT

        self.life -= 1  # Incorrect guess, lose a life
        if self.life <= 0:
            return GuessResult.LOSE  # No lives left, game over
        return GuessResult.INCORRECT

    def get_display_state(self) -> dict:
        """Returns the values used for display state update as a dictionary.
        Returns:
            A dictionary containing the current score, lives,
                remaining regions, and game over status.
        """
        return {
            'score': self.score,
            'life': self.life,
            'remaining': self.remaining,
            'game_over': self.life <= 0 or self.remaining <= 0
        }

    def get_regions(self) -> dict:
        """Returns the found and altered regions as a dictionary."""
        return {
            'found_regions': self.found_regions,
            'altered_regions': self.altered_regions
        }

    def reveal(self) -> None:
        """Sets remaining regions to 0.
        Used for reveal button functionality."""
        self.remaining = 0
